### ISSUE TITLE
Discord server

### ISSUE THREAD

**Issue by ember-314** [QuiteAFancyEmerald/HolyUnblockerPublic#173]
When I create a Holy Unblocker site, it says to visit the discord for official site links and other useful things. But when I use the provided discord invite, (https://discord.com/invite/hcUUceSCtj,) it tells me its invalid. Am I missing something or Is there any way I can join/visit the Titanium Network discord? Thanks!

Edit: I have already noticed the pinned issue, which says:
More information:
This issue has now been pinned due to the number of users asking for more mirrors due to these "reasons":

"I don't have another device or Discord"
"I can't access Discord"
"I would rather not join the Discord or have some other odd reason"

I am aware of this, and a solution the owners of the Titanium Network discord can try is generating a new/permanent link, or upgrading the server for more capacity. There is no point in advertising a discord if it is useless, and considering a lot of usage of this project is being able to generate new 'official' sites from the discord, this will render this project to a lot of people useless. If you are unwilling to upgrade the discord server for a larger capacity or a longer lasting invite link, then I suggest you make an 'official' website generator somewhere else, or publish an 'official' copy of the repository.

**Comment by QuiteAFancyEmerald** [comment]
We have an official Discord link lol (discord.gg/unblock)
No need for the huge paragraph. The old invite link worked for well over a year with over 7k+ joins through it but was recently revoked on accident by a staff member. For whatever reason I still need to update the source here along with the main HU site. Otherwise the new invite can be found on any of the sites.

Lastly our server has perfect capacity for a vanity URL, etc... just note the mistake above whoops

New Invite: https://discord.gg/CwWpdGkuWY
Official Invite: https://discord.gg/unblock

**Comment by ember-314** [comment]
extremely sorry if I came across forceful or rude- my bad for missing the new invite

**Comment by QuiteAFancyEmerald** [comment]
No worries! :D
