### ISSUE TITLE
Game Requests (PR/Issues)

### ISSUE THREAD

**Issue by Rockpods** [QuiteAFancyEmerald/HolyUnblockerPublic#190]
# Game Request Index
**Regarding PRs:** Please scroll down below to view a detailed guide on creating PRs containing game requests

### Formating:
**(Number from newest):** Links to game or something similar if provided
**More Info:** Pre-existing information obtained from the issue creator if found
**NOTES:** RESPONSE FROM EMERALD OR OLYB TO REQUEST
**Link:** Links to the issue.

## Index

No active jobs.

### If you do not follow this your request may be declined.
**Game Description (Follow the basic structure of the page. I will provide an example):**
https://github.com/titaniumnetwork-dev/Holy-Unblocker/blob/master/views/pages/nav/games5.html
```html
<div class="responsive">
        <div class="gallery">
            <a id="idusedbynavscript" href="#">
                <img src="/assets/img/example.png" alt="Co&#8203;ol Game">
            </a>
            <div class="desc">
                <p style="font-weight: bold;">Epic desc&#8203;ription 
            </div>
        </div>
</div>
```

**Game Image (Upload your game image here... try to make it a square and not blurry):**
https://github.com/titaniumnetwork-dev/Holy-Unblocker/tree/master/views/assets/img

**Game Assets (anything in the archive folder. /g for pretty much everything):**
https://github.com/titaniumnetwork-dev/Holy-Unblocker/tree/master/views/archive

Flash games (if they work with Ruffle) need to be sent to OlyB/@BinBashBanana  (tell me beforehand) along with any games within the Emulibrary. You will need to verify that its working before you send or message me anything via webretro or Ruffle.

**Navigation HTML5, etc. (add the proper path below line 43):**
https://github.com/titaniumnetwork-dev/Holy-Unblocker/blob/master/views/expr/

**Navigation Flash (once again add the proper path):**
https://github.com/titaniumnetwork-dev/Holy-Unblocker/blob/master/views/expr/flash-nav.js

**Navigation Emulibrary:**
DM me or OlyB/@BinBashBanana about this and we will set this up since the actual source regarding any of the Emulators or EmuLibrary is closed.

**Comment by QuiteAFancyEmerald** [comment]
tysm! <3

**Comment by QuiteAFancyEmerald** [comment]
# Explanation on Creating PRs with Game Requests
### If you do not follow this your request may be declined.
**Game Description (Follow the basic structure of the page. I will provide an example):**
https://github.com/titaniumnetwork-dev/Holy-Unblocker/blob/master/views/pages/nav/games5.html
```html
<div class="responsive">
        <div class="gallery">
            <a id="idusedbynavscript" href="#">
                <img src="/assets/img/example.png" alt="Co&#8203;ol Game">
            </a>
            <div class="desc">
                <p style="font-weight: bold;">Epic desc&#8203;ription 
            </div>
        </div>
</div>
```

**Game Image (Upload your game image here... try to make it a square and not blurry):**
https://github.com/titaniumnetwork-dev/Holy-Unblocker/tree/master/views/assets/img

**Game Assets (anything in the archive folder. /g for pretty much everything):**
https://github.com/titaniumnetwork-dev/Holy-Unblocker/tree/master/views/archive

Flash games (if they work with Ruffle) need to be sent to OlyB (tell me beforehand) along with any games within the Emulibrary. You will need to verify that its working before you send or message me anything via webretro or Ruffle.

**Navigation HTML5, etc. (add the proper path below line 43):**
https://github.com/titaniumnetwork-dev/Holy-Unblocker/blob/master/views/expr/

**Navigation Flash (once again add the proper path):**
https://github.com/titaniumnetwork-dev/Holy-Unblocker/blob/master/views/expr/flash-nav.js

**Navigation Emulibrary:**
DM me or OlyB about this and we will set this up since the actual source regarding any of the Emulators or EmuLibrary is closed.

**Comment by Rockpods** [comment]
I am going to be updating when I get the chance

**Comment by BinBashBanana** [comment]
@Rockpods I was actually working on an update for this, games will be dynamically loaded into the page with javascript. Hopefully it will make adding more games much easier!

**Comment by Rockpods** [comment]
> @Rockpods I was actually working on an update for this, games will be dynamically loaded into the page with javascript. Hopefully it will make adding more games much easier!

I just meant updating the game requests list
