### ISSUE TITLE
Deploying on Heroku makes it so that most of the website doesnt work

### ISSUE THREAD

**Issue by skunksecond** [QuiteAFancyEmerald/HolyUnblockerPublic#208]
Title says it all, im having issues with my version of the site, games dont load and some unblockers dont work.

**Comment by s191ed** [comment]
deploying sucks, use one of the proxies the server [https://discord.gg/unblock] to get the actual proxy so all the unblockers work and its up to date. holyunblocker dosent work right now so you might as well just stick to your heroku, but if you need a link heres one: [https://blazingscience.xyz] (note that it goes to incognito instead of holyunblocker because like i said, holyunblocker is down because of low fundings).

**Comment by Nebelung-Dev** [comment]
dont leak links

**Comment by QuiteAFancyEmerald** [comment]
Yep! You didn't setup external proxies at all correctly. Check out some of the past issues here regarding things or read over the README :D
