### ISSUE TITLE
Cheat code

### ISSUE THREAD

**Issue by JoeyMeepLand** [QuiteAFancyEmerald/HolyUnblockerPublic#239]
No one knows how to use cheat code on pokemon game thay know how to get to the pontie of adding the code but now how to enter them correctly could some one exsplane this for pokemon emreald

**Comment by SubduedCyns** [comment]
To insert a cheat follow these steps.
1. Open the game
2. Open "Menu"
3. Scroll down to cheats
4. Open cheats
5. Click "Add new cheat to bottom/top"
6. Click that new cheat.
7. Click code, and Paste/Type the code.
8. You can name the code with description, though it is optional.
9. exit that cheat, and click "Apply changes"
10. Done, though please be aware that some cheats will not work because they may be outdated, but some cheats will just not work.

**Comment by JoeyMeepLand** [comment]
ok then where do you get the code and how do you use them

**Comment by SubduedCyns** [comment]
You can gets the cheats from anywhere,sites for ROM hacks include pokemoncoder.
Though you can just search "(insert game) cheat codes.
For the second question, I had said in my original comment.

**Comment by QuiteAFancyEmerald** [comment]
tyty for the detailed answering
