### ISSUE TITLE
A new issue on discord proxy for UV (QR Login)

### ISSUE THREAD

**Issue by L0stMem** [QuiteAFancyEmerald/HolyUnblockerPublic#319]
So it looks like womgix discord still doesnt work however ultraviolet does. There is a issue about that if you login using qr code. If you start up discord it will say “looks like discord has crashed unexpectedly” every time.

**Comment by QuiteAFancyEmerald** [comment]
Yep! I recognized this issue earlier. I'm actually going to be removing Womginx as an option due to the lack of support it has to hCaptcha now and replacing it with Rammerhead. Regarding UV, you have a ~five second window to have the code scanned. Like its a really short window. I'll forward this to Duce (the developer of UV).

**Comment by L0stMem** [comment]
When will this issue be fixed, as i want to use discord again.

**Comment by L0stMem** [comment]
@QuiteAFancyEmerald Can you please answer me follow up question.
