### ISSUE TITLE
Geforce Now

### ISSUE THREAD

**Issue by Senshi209** [QuiteAFancyEmerald/HolyUnblockerPublic#352]
When I click on geforce now, nothing happens. Somebody pls help

**Comment by Zubbbz** [comment]
it doesn't work. If it did work, it wouldn't work well. It would be laggy, and have lots of compression artifacts because the proxies used wouldn't be quick enough to support a service like geforce now. also some websites just aren't going to work while using a service like holy unblocker, which by the way is free (the creator doesnt owe you anything, and you should be thankful they made it public at all). Now if you are an egghead then what you should take away is that Geforce Now doesnt't work on holy unblocker and it probably never will. Don't ask why. It just wont. Stop misusing GH issues. 😦
