### ISSUE TITLE
local deploy error

### ISSUE THREAD

**Issue by porgman101** [QuiteAFancyEmerald/HolyUnblockerPublic#411]
When I deploy it locally on GitHub code spaces it cannot seem to run or deploy the webpage this is also the case for doge unblocked could it be a code spaces thing?

**Comment by proudparrot2** [comment]
Yeah seems like something with dependencies aren't going right
cc @QuiteAFancyEmerald 

![CleanShot 2024-09-24 at 17 57 49@2x](https://github.com/user-attachments/assets/15112541-2811-42c8-b8ba-6156e0810d1a)

**Comment by QuiteAFancyEmerald** [comment]
I'll look into it

**Comment by QuiteAFancyEmerald** [comment]
I've determined the root issue to be GitHub Codespace determining the repository needs Node v16. This has been fixed with the latest commit with a configuration file that will automatically import when you create a new GitHub Codespace.

When you run the project utilize `npm install` and `npm start`
